# -*- coding: utf-8 -*-
"""Problem2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19arzpphBWK_FJUnEKW11auSwOpYCEZQG
"""

# Two Sum 
# Leetcode 
# Problem 1
# S30 Big N Problem #28 {Easy }

def twoSum(nums, target):
    
    
    d = {}
    
    for i in range(len(nums)):
        if nums[i] not in d:
            d[target-nums[i]] = i
        else:
            return d[nums[i]],i

l = [2,7,11,5]
target = 9
print(twoSum(l, target))

